apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-frontend
  template:
    metadata:
      labels:
        app: nginx-frontend
    spec:
      containers:
      - name: nginx-frontend
        image: karthequian/helloworld:latest
        resources:
          limits:
            memory: "500Mi"
            cpu: "700m"
          requests:
            memory: "500Mi"
            cpu: "200m"
        ports:
        - name: web-port
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-frontend
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: web-port
  selector:
    app: nginx-frontend